// single-word or multi-word phrases that are strong indicators of spam when found
// in user profiles or comments. matched using word boundaries for prose contexts.
//
// be conservative adding single words -- prefer multi-word phrases that are
// unambiguous in an academic context.

export const communitySpamPhrases = [
	// adult / escort
	'escorts',
	'escort',
	'escort service',
	'call girls',
	'call girl',
	'independent escort',
	'female escort',
	'male escort',
	'stripper',
	'porn',
	'naked',
	'sexy',
	'cams',
	'orgasm',
	'orgasms',
	'sex',
	'erotic massage',
	'nuru massage',
	'sensual massage',
	'body rub',
	'adult entertainment',
	'hookup',
	'one night stand',
	'happy ending',
	'incall',
	'outcall',

	// gambling / betting
	'casino',
	'lottery',
	'slots',
	'slot',
	'poker',
	'betting',
	'sportsbook',
	'baccarat',
	'online casino',
	'live casino',
	'free spins',
	'jackpot',
	'roulette',
	'blackjack',
	'bonus code',

	// services / promotion
	'seo',
	'search engine optimization',
	'digital strategies',
	'power washing',
	'real estate',
	'health service',
	'building company',
	'construction company',
	'personal injury lawyer',
	'visit our website',
	'click here',
	'contact us today',
	'book now',
	'order now',
	'hire us',
	'we provide',
	'we offer',
	'our services',
	'free estimate',
	'limited time offer',
	'act now',
	'100% guaranteed',

	// hacking / recovery
	'ethical hacker',
	'hacking services',
	'phone spy',
	'spy on',
	'funds recovery',
	'recovery service',
	'lost crypto',
	'stolen crypto',
	'crypto recovery',

	// substances
	'vape',
	'disposable vape',
	'cannabis',
	'marijuana',
	'edibles',
	'ivermectin',
	'viagra',
	'cialis',
	'diet pill',
	'weight loss',
	'testosterone booster',

	// financial / mlm
	'forex trading',
	'binary option',
	'passive income',
	'make money online',
	'investment opportunity',
	'guaranteed returns',
	'financial freedom',

	// supernatural / scam
	'love spell',
	'spell caster',
	'get your ex back',
	'bring back your lover',
	'black magic',
	'voodoo',

	// commerce spam
	'shopping',
	'vendor',
	'online seller',
	'delivery',
	'buy',
	'buying',
	'purchase',
	'sell',
	'selling',
	'cash',
	'competitive rates',
	'best deals',
	'affordable prices',
	'free quotes',
	'affordable',
	'apk',
	'full movie',
	'geometry dash',

	// generic spam openers (multi-word so they don't false-positive on normal prose)
	'my name is',
	'we are a',
	'we are an',
	'are you looking',
	'would you like',
	'do you need',
	'we supply',
	'our website',
	'our site',
	'if you are looking',
	'reach out to us',
	'whatsapp us',
	'contact us on whatsapp',
	'contact us on telegram',

	// exams / dumps (common cert-dump spam)
	'dumps',
	'exams',
	'tests',
	'clients',
	'download',
];
