#!/usr/bin/env bash
set -euo pipefail

# Download font files from npm (fontsource), upload to S3 under a
# content-hashed directory, and update source files to point at it.
#
# Files are uploaded to: s3://assets.pubpub.org/_fonts/<hash>/
# The hash is derived from the content of all generated files, so
# updating fonts always produces a new URL — no cache purging needed.
#
# This is a one-time (or rare) script — run it when adding or updating fonts.
# No fontsource npm packages need to be installed in the project.
#
# Prerequisites:
#   - AWS CLI configured (credentials in env or ~/.aws/credentials)
#   - curl, tar, sed, shasum
#
# Usage:
#   scripts/upload-fonts-to-s3.sh            # download, upload, update source files
#   scripts/upload-fonts-to-s3.sh --dry-run  # download + preview, skip upload

BUCKET="assets.pubpub.org"
S3_BASE="_fonts"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
	DRY_RUN=true
	echo "=== DRY RUN — no files will be uploaded ==="
	echo
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
EXPORT_HTML="$ROOT_DIR/workers/tasks/export/html.tsx"
SERVER_HTML="$ROOT_DIR/server/Html.tsx"
WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

STAGING_DIR="$WORK_DIR/upload"
PKG_DIR="$WORK_DIR/packages"
mkdir -p "$STAGING_DIR" "$PKG_DIR"

# ---------------------------------------------------------------------------
# Verify AWS credentials before doing anything slow
# ---------------------------------------------------------------------------

if [[ "$DRY_RUN" == "false" ]]; then
	echo "Verifying AWS credentials..."
	if ! aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
		echo "ERROR: Cannot access s3://$BUCKET/"
		echo "Check that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set correctly."
		echo "You can test with: aws s3 ls s3://$BUCKET/ --max-items 1"
		exit 1
	fi
	echo "AWS credentials OK."
	echo
fi

# ---------------------------------------------------------------------------
# Font packages to download from npm
# ---------------------------------------------------------------------------

PACKAGES=(
	"@fontsource-variable/source-sans-3"
	"@fontsource-variable/source-serif-4"
	"@fontsource-variable/outfit"
	"@fontsource-variable/noto-serif-tc"
	"@fontsource-variable/noto-serif-jp"
	"@fontsource-variable/noto-serif-kr"
	"@fontsource-variable/noto-serif-sc"
	"@fontsource-variable/noto-sans-tc"
	"@fontsource-variable/noto-sans-jp"
	"@fontsource-variable/noto-sans-kr"
	"@fontsource-variable/noto-sans-sc"
)

# ---------------------------------------------------------------------------
# Download and extract packages directly from npm registry
# ---------------------------------------------------------------------------

echo "Downloading font packages from npm..."

for pkg in "${PACKAGES[@]}"; do
	short_name="${pkg#@fontsource-variable/}"
	echo "  $pkg"

	tarball_url=$(npm view "$pkg" dist.tarball 2>/dev/null)
	if [[ -z "$tarball_url" ]]; then
		echo "ERROR: Could not find $pkg on npm"
		exit 1
	fi

	pkg_extract="$PKG_DIR/$short_name"
	mkdir -p "$pkg_extract"
	curl -sL "$tarball_url" | tar xz -C "$pkg_extract" --strip-components=1

	# Copy woff2 files to staging
	if [[ -d "$pkg_extract/files" ]]; then
		cp "$pkg_extract/files"/*.woff2 "$STAGING_DIR/" 2>/dev/null || true
	fi
done

TOTAL_WOFF2=$(ls "$STAGING_DIR"/*.woff2 2>/dev/null | wc -l | tr -d ' ')
echo
echo "Downloaded $TOTAL_WOFF2 woff2 files"
echo

# ---------------------------------------------------------------------------
# Generate fonts.css and fonts-cjk.css (hosted on S3 alongside the woff2 files)
# ---------------------------------------------------------------------------

# Helper: process a list of CSS_SOURCES entries into a CSS file.
# woff2 files are referenced with relative url() since CSS lives alongside them.
generate_css() {
	local output_file="$1"
	shift
	local sources=("$@")

	{
		echo "/* Auto-generated by scripts/upload-fonts-to-s3.sh */"
		echo

		for entry in "${sources[@]}"; do
			IFS=':' read -r short_name css_file family_override <<< "$entry"
			css_path="$PKG_DIR/$short_name/$css_file"

			if [[ ! -f "$css_path" ]]; then
				echo "WARNING: $css_path not found, skipping" >&2
				continue
			fi

			echo "/* === $family_override ($css_file) === */"

			sed -E \
				-e "s|font-family: '[^']*Variable'|font-family: '${family_override}'|g" \
				-e "s|url\(\./files/([^)]+)\)|url(\1)|g" \
				-e "s|format\('woff2-variations'\)|format('woff2')|g" \
				"$css_path"

			echo
		done
	} > "$output_file"

	local faces size
	faces=$(grep -c "@font-face" "$output_file")
	size=$(wc -c < "$output_file" | tr -d ' ')
	echo "  $(basename "$output_file"): $faces @font-face rules, ${size} bytes"
}

# All font sources: main + CJK in a single fonts.css
CSS_SOURCES=(
	# Main fonts
	"source-sans-3:index.css:Source Sans 3"
	"source-sans-3:wght-italic.css:Source Sans 3"
	"source-serif-4:index.css:Source Serif 4"
	"source-serif-4:wght-italic.css:Source Serif 4"
	"outfit:index.css:Outfit"
	# CJK fonts (Noto Serif + Noto Sans for TC, JP, KR, SC)
	"noto-serif-tc:index.css:Noto Serif TC"
	"noto-serif-jp:index.css:Noto Serif JP"
	"noto-serif-kr:index.css:Noto Serif KR"
	"noto-serif-sc:index.css:Noto Serif SC"
	"noto-sans-tc:index.css:Noto Sans TC"
	"noto-sans-jp:index.css:Noto Sans JP"
	"noto-sans-kr:index.css:Noto Sans KR"
	"noto-sans-sc:index.css:Noto Sans SC"
)

echo "Generating fonts.css..."
generate_css "$STAGING_DIR/fonts.css" "${CSS_SOURCES[@]}"
echo

# ---------------------------------------------------------------------------
# Compute content hash from all generated files
# ---------------------------------------------------------------------------

CONTENT_HASH=$(find "$STAGING_DIR" -type f | sort | xargs cat | shasum -a 256 | cut -c1-8)
S3_PREFIX="$S3_BASE/$CONTENT_HASH"
BASE_URL="https://$BUCKET/$S3_PREFIX"

echo "Content hash: $CONTENT_HASH"
echo "S3 path:      s3://$BUCKET/$S3_PREFIX/"
echo "Public URL:   $BASE_URL/"
echo

# ---------------------------------------------------------------------------
# Upload to S3
# ---------------------------------------------------------------------------

if [[ "$DRY_RUN" == "false" ]]; then
	echo "Uploading to s3://$BUCKET/$S3_PREFIX/ ..."

	# Upload woff2 files with long cache
	aws s3 sync "$STAGING_DIR/" "s3://$BUCKET/$S3_PREFIX/" \
		--acl public-read \
		--cache-control "public, max-age=31536000, immutable" \
		--exclude "*" --include "*.woff2" \
		--content-type "font/woff2"

	# Upload CSS files
	for css in "$STAGING_DIR"/*.css; do
		aws s3 cp "$css" "s3://$BUCKET/$S3_PREFIX/$(basename "$css")" \
			--acl public-read \
			--cache-control "public, max-age=31536000, immutable" \
			--content-type "text/css"
	done

	echo "Upload complete."
else
	echo "Would upload $TOTAL_WOFF2 woff2 files + fonts.css to s3://$BUCKET/$S3_PREFIX/"
fi

echo

# ---------------------------------------------------------------------------
# Update source files to point at the new hashed URL
# ---------------------------------------------------------------------------

# 1. server/Html.tsx — fonts <link> href
sed -i '' -E \
	"s|href=\"https://assets.pubpub.org/_fonts/[^\"]+/fonts.css\"|href=\"${BASE_URL}/fonts.css\"|" \
	"$SERVER_HTML"
echo "Updated $SERVER_HTML"

# 2. workers/tasks/export/html.tsx — fontsHref constant
sed -i '' -E \
	"s|const fontsHref = '.*';|const fontsHref = '${BASE_URL}/fonts.css';|" \
	"$EXPORT_HTML"
echo "Updated $EXPORT_HTML"

echo
echo "Done! Commit the changes."
